# Generated by Django 2.0.1 on 2018-03-06 14:23

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('TeamSize', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Events', models.ManyToManyField(to='website.Event')),
                ('Members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
